(function(g){var window=this;var jwa=function(a,b,c,d){var e=b.gc();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.dc(c,d?d:"mqdefault.jpg");var k=b instanceof g.sP?g.TV(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.YQ(f).type,m=b instanceof g.sP?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.cn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.$Q&&(c.playlist_length=b.getLength());a.update(c)},T7=function(a,b){g.NV.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.O=!1},U7=function(a){var b={H:"div",
N:"ytp-upnext",T:{"aria-label":"{{watch}}"},L:[{H:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{H:"span",N:"ytp-upnext-top",L:[{H:"span",N:"ytp-upnext-header",L:[g.T("YTP_PLAYLIST_UP_NEXT")]},{H:"span",N:"ytp-upnext-title",L:["{{title}}"]},{H:"span",N:"ytp-upnext-author",L:["{{author}}"]}]},{H:"a",N:"ytp-upnext-autoplay-icon",T:{href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")},L:[{H:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},L:[{H:"circle",
N:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",N:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",N:"ytp-upnext-bottom",L:[{H:"span",N:"ytp-upnext-cancel"},{H:"span",N:"ytp-upnext-paused",L:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",N:"ytp-upnext-close"}]};g.X.call(this,b);this.B=null;var c=this.va["ytp-upnext-cancel"],b=this.va["ytp-upnext-close"];this.B=new g.X({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:0,"aria-label":g.T("YTP_AUTOPLAY_CANCEL")},L:[g.T("YTP_CANCEL")]});g.L(this,this.B);this.B.W("click",this.eA,this);this.B.Ea(c);c=new g.X({H:"button",ca:["ytp-upnext-close-button","ytp-button"],T:{"aria-label":g.T("YTP_AUTOPLAY_CANCEL")}});g.L(this,c);c.W("click",this.eA,this);c.Ea(b);this.o=
a;this.K=this.va["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Bt(this.Bm,5E3,this);g.L(this,this.G);this.J=0;this.R(this.va["ytp-upnext-autoplay-icon"],"click",this.OP);this.bA();this.R(a,"autonavvisibility",this.bA);this.R(a,"mdxnowautoplaying",this.eP);this.R(a,"mdxautoplaycanceled",this.fP);this.R(a,"mdxautoplayupnext",this.iC);3==this.o.Wa()&&(a=(a=g.QU(g.LU(this.o)))?a.nH():null)&&this.iC(a)},kwa=function(a,b){a.C=b;
jwa(a,b,g.W(a.o),"hqdefault.jpg")},V7=function(a,b){a.A||(g.oG("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.J=(0,g.BG)(),a.A=new g.Bt((0,g.y)(a.Gp,a,b),25),a.Gp(b));
g.Qp(a.element,"ytp-upnext-autoplay-paused")},X7=function(a){W7(a);
a.J=(0,g.BG)();a.Gp();g.R(a.element,"ytp-upnext-autoplay-paused")},W7=function(a){a.A&&(a.A.dispose(),a.A=null)},lwa=function(a){T7.call(this,a,"subscribecard-endscreen");
var b=a.ha();this.A=new g.X({H:"div",N:"ytp-subscribe-card",L:[{H:"img",N:"ytp-author-image",T:{src:b.profilePicture}},{H:"div",N:"ytp-subscribe-card-right",L:[{H:"div",N:"ytp-author-name",L:[b.author]},{H:"div",N:"html5-subscribe-button-container"}]}]});g.L(this,this.A);this.A.Ea(this.element);this.B=new g.E1(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.zl,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.B);this.B.Ea(this.A.va["html5-subscribe-button-container"]);this.hide()},
Y7=function(a){var b=g.W(a),b=b.A&&!b.F;
g.X.call(this,{H:"a",N:"ytp-videowall-still",T:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{H:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{H:"span",N:"ytp-videowall-still-info",L:[{H:"span",N:"ytp-videowall-still-info-bg",L:[{H:"span",N:"ytp-videowall-still-info-content",T:g.cF||g.Te?{style:"will-change: opacity"}:void 0,L:[{H:"span",N:"ytp-videowall-still-info-title",L:["{{title}}"]},
{H:"span",N:"ytp-videowall-still-info-author",L:["{{author_and_views}}"]},{H:"span",N:"ytp-videowall-still-info-live",L:[g.T("YTP_LIVE")]},{H:"span",N:"ytp-videowall-still-info-duration",L:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (",{H:"span",L:["{{playlist_length}}"]},")"]}]},{H:"span",ca:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.W("click",this.C);this.W("keypress",this.D);if(g.W(a).da){a=a.app.da;b=this.element;g.ib(a.A,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.Oe(this,(0,g.y)(a.F,a,b))}},Z7=function(a){T7.call(this,a,"videowall-endscreen");
this.ba=a;this.G=0;this.B=[];this.J=this.D=this.C=null;this.K=this.U=!1;this.F=new g.XF(this);g.L(this,this.F);this.M=new g.Bt(g.za(g.R,this.element,"ytp-show-tiles"),0);g.L(this,this.M);var b=new g.X({H:"button",ca:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.T("YTP_PREVIOUS")},L:[g.cE()]});g.L(this,b);b.Ea(this.element);b.W("click",this.GL,this);this.P=new g.GV({H:"div",N:"ytp-endscreen-content"});g.L(this,this.P);this.P.Ea(this.element);b=new g.X({H:"button",ca:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":g.T("YTP_NEXT")},L:[g.dE()]});g.L(this,b);b.Ea(this.element);b.W("click",this.FL,this);this.A=new U7(a);g.L(this,this.A);g.mV(this.o,this.A.element,4);this.hide()},$7=function(a){return g.nV(a.o)&&a.Kp()&&!a.J},mwa=function(a){return(0,g.H)(a.ag,function(a){return g.MZ(a)})},nwa=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.W(a.o).experiments.g("video_wall_emphasize_first")?4:2},a8=function(a){var b=a.ds();
b!=a.U&&(a.U=b,a.o.Y("autonavvisibility"))},b8=function(a){g.AV.call(this,a);
g.ZD({});this.o=null;this.isAvailable=!0;this.A=new g.XF(this);g.L(this,this.A);this.B=g.W(a);owa(a)?this.o=new Z7(this.g):this.B.ra?this.o=new lwa(this.g):this.o=new T7(this.g);g.L(this,this.o);g.mV(this.g,this.o.element,4);this.mB();this.A.R(a,"videodatachange",this.mB,this);this.A.R(a,"crn_endscreen",this.hL,this);this.A.R(a,"crx_endscreen",this.iL,this)},owa=function(a){a=g.W(a);
return a.Kc&&!a.ra};g.p(T7,g.NV);T7.prototype.create=function(){this.O=!0};
T7.prototype.destroy=function(){this.O=!1};
T7.prototype.Kp=function(){return!1};
T7.prototype.ds=function(){return!1};g.p(U7,g.X);g.h=U7.prototype;g.h.Bm=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.bA=function(){g.MV(this,g.MU(this.o))};
g.h.FP=function(){window.focus();this.Bm()};
g.h.hide=function(){g.X.prototype.hide.call(this)};
g.h.Gp=function(a){a=a||g.W(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.BG)()-this.J,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Wa()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.W(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.$U(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.gc(),this.Bm(),this.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.dc(b)}),this.F=this.R(this.D,"click",this.FP),this.G.start())}W7(this);
this.o.pj(!1,a)};
g.h.OP=function(a){!g.Ae(this.B.element,g.NF(a))&&g.wZ(a,this.o)&&this.select()};
g.h.eA=function(){g.aV(this.o,"autonavcancel");g.OU(this.o,!0)};
g.h.eP=function(a){this.o.Wa();this.show();V7(this,a)};
g.h.iC=function(a){this.o.Wa();this.C&&this.C.gc().videoId==a.gc().videoId||kwa(this,a)};
g.h.fP=function(){this.o.Wa();W7(this);this.hide()};
g.h.X=function(){W7(this);this.Bm();g.X.prototype.X.call(this)};g.p(lwa,T7);g.p(Y7,g.X);Y7.prototype.Dj=function(){var a=this.A.gc().videoId,b=this.A.getPlaylistId();g.r2(this.o.app,a,this.A.Td,b,void 0,void 0)};
Y7.prototype.C=function(a){g.qV(this.o,this.element);g.wZ(a,this.o,this.B,this.A.Td||void 0)&&this.Dj()};
Y7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.SF(a)||(this.Dj(),g.UF(a))}};g.p(Z7,T7);g.h=Z7.prototype;g.h.create=function(){T7.prototype.create.call(this);var a=this.o.ha();a&&(this.C=mwa(a),this.D=a);this.oh();this.F.R(this.o,"appresize",this.oh);this.F.R(this.o,"videodatachange",this.HL);this.F.R(this.o,"autonavchange",this.dz);this.F.R(this.o,"autonavcancel",this.DL);this.F.R(this.element,"transitionend",this.VQ)};
g.h.destroy=function(){g.ZF(this.F);g.Qe(this.B);this.B=[];this.C=null;T7.prototype.destroy.call(this);g.Qp(this.element,"ytp-show-tiles");this.M.stop()};
g.h.Kp=function(){return 1!=this.D.autonavState};
g.h.show=function(){T7.prototype.show.call(this);g.Qp(this.element,"ytp-show-tiles");g.W(this.o).isMobile?g.Ct(this.M):this.M.start();(this.K||this.J&&this.J!=this.D.clientPlaybackNonce)&&g.OU(this.o,!1);var a=$7(this);g.nV(this.o)&&g.W(this.o).experiments.g("ui_logging")&&g.$U(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Kp()?"enabled":"disabled"});a?(a8(this),2==this.D.autonavState?g.W(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.In()?this.A.select(!0):V7(this.A):3==this.D.autonavState&&
X7(this.A)):(g.OU(this.o,!0),a8(this))};
g.h.hide=function(){T7.prototype.hide.call(this);X7(this.A);a8(this)};
g.h.VQ=function(a){g.NF(a)==this.element&&this.oh()};
g.h.oh=function(){if(this.C&&this.C.length){g.R(this.element,"ytp-endscreen-paginate");var a=g.xh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=nwa(this,0,k),q=nwa(this,1,k);var r=l*m+(Math.pow(n,2)-m);r+=Math.pow(q,2)-m;for(r-=m;0<r&&(d<f||e<k);){var w=d/2,A=e/2,D=d<=f-2&&r>=A*m,B=e<=k-2&&r>=w*m;if((w+1)/A*c/b>b/(w/(A+1)*c)&&B)r-=w*m,e+=2;else if(D)r-=A*m,d+=2;else if(B)r-=w*m,e+=2;else break}c=!1;f=2+n;r>=3*
m&&6>=l*m-r&&(e>=f||d>=f)&&2>=q&&(c=!0);m=96*d;r=54*e;b=m/r<b?a.height/r:a.width/m;b=Math.min(b,2);m*=b;r*=b;m*=g.Ld(a.width/m||1,1,1.21);r*=g.Ld(a.height/r||1,1,1.21);m=Math.floor(Math.min(a.width,m));r=Math.floor(Math.min(a.height,r));a=this.P.element;g.wh(a,m,r);g.eh(a,{marginLeft:m/-2+"px",marginTop:r/-2+"px"});kwa(this.A,this.C[0]);g.S(this.element,"ytp-endscreen-takeover",$7(this));a8(this);m+=4;r+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(A=2<q&&1<=b&&!f?b+1:b,D=0,c&&k>=d-2&&w>=e-2?D=1:
0==w%2&&0==k%2&&(w<n&&k<n?0==w&&0==k&&(D=n):2<q&&w>=e-q&&k>=d-q?w==e-q&&k==d-q&&(f=!0,A=1,D=q):D=2),A=g.Md(A+this.G,l),0!=D){B=this.B[b];B||(B=new Y7(this.o),this.B[b]=B,a.appendChild(B.element));var M=Math.floor(r*w/e),Z=Math.floor(m*k/d),Za=Math.floor(r*(w+D)/e)-M-4,lb=Math.floor(m*(k+D)/d)-Z-4;g.lh(B.element,Z,M);g.wh(B.element,lb,Za);g.eh(B.element,"transitionDelay",(w+k)/20+"s");g.S(B.element,"ytp-videowall-still-mini",1==D);g.S(B.element,"ytp-videowall-still-large",2<D);D=B;A=this.C[A];D.A=
A;jwa(D,A,g.W(D.o),g.Op(D.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");B=A.Td;A=D.o;g.W(A).da&&(A=A.app.da,B=B&&B.itct,D=D.element.getAttribute("data-visual-id"),g.oV(A,"onLogServerVeCreated",{id:D,tracking_params:B}));b++}g.S(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.te(e.element),g.Pe(e);this.B.length=b}};
g.h.HL=function(){var a=this.o.ha();this.D!=a&&(this.G=0,this.C=mwa(a),this.D=a,this.oh())};
g.h.FL=function(){this.G+=this.B.length;this.oh()};
g.h.GL=function(){this.G-=this.B.length;this.oh()};
g.h.xJ=function(){return!!this.A.A};
g.h.dz=function(a){1==a?(this.K=!1,this.J=this.D.clientPlaybackNonce,W7(this.A),this.g&&this.oh()):(this.K=!0,this.g&&$7(this)&&(2==a?V7(this.A):3==a&&X7(this.A)))};
g.h.DL=function(a){if(a){for(a=0;a<this.B.length;a++)g.rV(this.ba,this.B[a].element,!0);this.dz(1)}else this.J=null,this.K=!1;this.oh()};
g.h.ds=function(){return this.g&&$7(this)};g.p(b8,g.AV);g.h=b8.prototype;g.h.Zy=function(){var a=this.g.ha(),b=!owa(this.g)||!(!a.ag||!a.ag.length),a=g.NP(a,"ypc_module"),c=g.s2(this.g.app);return(b||!1)&&!a&&!c};
g.h.Yy=function(){return this.o.ds()};
g.h.uJ=function(){return this.Yy()?this.o.xJ():!1};
g.h.X=function(){g.iV(this.g,"endscreen");g.AV.prototype.X.call(this)};
g.h.load=function(){g.AV.prototype.load.call(this);this.o.show();g.W(this.g).ra&&.01>Math.random()&&g.$U(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.AV.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.hL=function(a){this.Zy()&&(this.o.O||this.o.create(),"load"==a.getId()&&this.load())};
g.h.iL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.mB=function(){g.iV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ha().lengthSeconds-10),0),a=new g.xJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.xJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.fV(this.g,[a,b])};g.WV("endscreen",b8);})(_yt_player);
