(function(g){var window=this;var Qwa=function(a,b){var c=[];g.Ll(b,function(a){try{var b=g.wD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.vD(b)&&c.push(a):c.push(a)},a);
return c},Rwa=function(a,b){var c=Qwa(a,b);
(0,g.G)(c,function(a){g.wD.prototype.remove.call(this,a)},a)},A8=function(a,b){g.Z0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.V=a;this.F={};this.R(a,"onMdxReceiversChange",this.J);this.R(a,"presentingplayerstatechange",this.J);this.J()},Swa=function(){var a=g.UG;
Rwa(a,a.g.Xd(!0))},B8=function(a){g.wH.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.y)(this.xT,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.y)(this.HP,this)))},C8=function(a){g.jH("cloudview",a)},Twa=function(a){C8("setApiReady_ "+a);
g.qa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},D8=function(){return g.v("yt.mdx.remote.cloudview.instance_")},Uwa=function(a){g.lG[a]&&(a=g.lG[a],(0,g.G)(a,function(a){g.jG[a]&&delete g.jG[a]}),a.length=0)},E8=function(){return g.v("yt.mdx.remote.connection_")},F8=function(a){g.qa("yt.mdx.remote.connectData_",a,void 0)},Vwa=function(a){g.qa("yt.mdx.remote.currentScreenId_",a,void 0)},G8=function(){return g.v("yt.mdx.remote.currentScreenId_")},I8=function(){if(!H8){var a=g.v("yt.mdx.remote.screenService_");
H8=a?new B8(a):null}return H8},J8=function(a){g.qa("yt.mdx.remote.cloudview.initializing_",a,void 0)},K8=function(){return!!g.v("yt.mdx.remote.cloudview.apiReady_")},L8=function(a){C8("setCastInstalled_ "+a);
g.WG("yt-remote-cast-installed",a)},M8=function(a){g.jH("cloudview",a)},Wwa=function(a,b){D8().init(a,b)},N8=function(){return!!g.XG("yt-remote-cast-installed")},Xwa=function(){C8("dispose");
var a=D8();a&&a.dispose();g.qa("yt.mdx.remote.cloudview.instance_",null,void 0);Twa(!1);g.nG(O8);O8.length=0},Ywa=function(){var a=window.document.createElement("a");
g.Jd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},Zwa=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},$wa=function(a){var b=g.iG();
if(b)if(b.clear(a),a)Uwa(a);else for(var c in g.lG)Uwa(c)},P8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Q8=function(){return g.v("yt.mdx.remote.channelParams_")||{}},S8=function(a){var b=E8();
F8(null);a||Vwa("");g.qa("yt.mdx.remote.connection_",a,void 0);R8&&((0,g.G)(R8,function(b){b(a)}),R8.length=0);
b&&!a?g.qG("yt-remote-connection-change",!1):!b&&a&&g.qG("yt-remote-connection-change",!0)},axa=function(){return g.v("yt.mdx.remote.connectData_")},T8=function(){var a=G8();
if(!a)return null;var b=I8().fe();return g.vH(b,a)},bxa=function(a,b){L8(!0);
J8(!1);Wwa(a,function(a){a?(Twa(!0),g.oG("yt-remote-cast2-api-ready")):(M8("Failed to initialize cast API."),L8(!1),g.YG("yt-remote-cast-available"),g.YG("yt-remote-cast-receiver"),Xwa());b(a)})},cxa=function(){return N8()?D8()?D8().getCastSession():(M8("getCastSelector: Cast is not initialized."),null):(M8("getCastSelector: Cast API is not installed!"),null)},dxa=function(){var a=Ywa(),b=window.document.getElementById(a),c=b&&g.yF(b,"loaded");
c||b&&!c||(b=Zwa(a,function(){g.yF(b,"loaded")||(g.zF(b,"loaded","true"),g.oG(a),g.GE(g.za($wa,a),0))}))},exa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},fxa=function(){if(g.gpa){var a=2,b=g.Gh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Lh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ih,c)}},V8=function(a,b){G8();
T8()&&T8();Vwa(a.id);var c=new g.AI(U8,a,Q8());c.connect(b,axa());c.subscribe("beforeDisconnect",function(a){g.qG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){E8()&&(E8(),S8(null))});
S8(c)},W8=function(){var a=g.BH();
if(!a)return null;var b=I8().fe();return g.vH(b,a)},X8=function(a){g.jH("remote",a)},Y8=function(){var a=E8();
return!!a&&3!=a.getProxyState()},Z8=function(){K8()?D8().stopSession():M8("stopSession called before API ready.");
var a=E8();a&&(a.disconnect(1),S8(null))},gxa=function(){var a=I8().cd.$_gos();
var b=T8();b&&E8()&&(g.uH(a,b)||a.push(b));return exa(a)},a9=function(a,b){g.$F.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.KB;this.A=this.o=null;this.J=(0,g.y)(this.PN,this);this.F=(0,g.y)(this.bl,this);this.G=(0,g.y)(this.ON,this);this.K=(0,g.y)(this.cO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Yt,this),hxa(this))):c=3;0!=c&&(b?this.Yt(c):g.GE((0,g.y)(function(){this.Yt(c)},this),0));
var d=cxa();d&&$8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},b9=function(a){return new g.pI(a.B.getPlayerContextData())},ixa=function(a,b,c,d,e){var f=b9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.tI(f,b,d);g.t(c)&&(g.rI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);c9(a,"setPlaylist",l);e||d9(a,f)},hxa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.ZP,a),this))},a)},jxa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},e9=function(a,b){50>a.C.Mc()&&g.MB(a.C,b)},f9=function(a,b,c){var d=b9(a);
g.rI(d,c);-1E3!=d.g&&(d.g=b);d9(a,d)},c9=function(a,b,c){a.B.sendMessage(b,c)},d9=function(a,b){jxa(a);
a.B.setPlayerContextData(g.uI(b));hxa(a)},$8=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.bl(null));
a.A=b;a.A&&(g9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.bl(a.A.media[0]))},kxa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=b9(a);b.contentId!=d.videoId&&g9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.rI(d,a.o.getEstimatedTime());d9(a,d)}else g9("No cast media video. Ignoring state update.")},g9=function(a){g.jH("CP",a)},h9=function(a,b,c){return(0,g.y)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),c9(this,b,c))},a)},lxa=function(a,b){var c=!1;
D8()||(c=new g.jI(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.WG("yt-remote-cast-available",a);g.qG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){C8("onReceiverSelected: "+a.friendlyName);
g.WG("yt-remote-cast-receiver",a);g.qG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){C8("onReceiverResumed: "+a.friendlyName);
g.WG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){C8("onSessionChange: "+g.rH(a));
a||g.YG("yt-remote-cast-receiver");g.qG("yt-remote-cast2-session-change",a)}),g.qa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
C8("cloudview.createSingleton_: "+c);return c},mxa=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.cF||a},i9=function(a,b){K8()?D8().setConnectedScreenStatus(a,b):M8("setConnectedScreenStatus called before ready.")},nxa=function(){C8("clearCurrentReceiver");
g.YG("yt-remote-cast-receiver")},oxa=function(){if(P8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){fxa();a({command:"cast.sender.init"});return}}if(!window.chrome||P8("Edge"))g.Ih();else if(fxa(),P8("Android")&&P8("Chrome/")&&window.navigator.presentation){var a="",b=g.Eh();55<=b?a="55":50<=b&&(a="50");g.Lh("//www.gstatic.com/eureka/clank"+a+g.Jh,g.Ih)}else g.Mh(0)},pxa=function(a){a?(g.WG("yt-remote-session-app",a.app),g.WG("yt-remote-session-name",a.name)):(g.YG("yt-remote-session-app"),g.YG("yt-remote-session-name"));
g.qa("yt.mdx.remote.channelParams_",a,void 0)},qxa=function(){var a=Q8();
if(g.Ub(a)){var a=g.AH(),b=g.XG("yt-remote-session-name")||"",c=g.XG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.qa("yt.mdx.remote.channelParams_",a,void 0)}},rxa=function(){var a=W8();
a?(X8("Resume connection to: "+g.rH(a)),V8(a,0)):(g.JH(),nxa(),X8("Skipping connecting because no session screen found."))},sxa=function(a){X8("remote.onCastSessionChange_: "+g.rH(a));
if(a){var b=T8();b&&b.id==a.id?i9(b.id,"YouTube TV"):(b&&Z8(),V8(a,1))}else E8()&&Z8()},txa=function(){var a=gxa(),b=T8();
b||(b=W8());return g.$a(a,function(a){return b&&g.oH(b,a.key)?!0:!1})},uxa=function(){var a=g.XG("yt-remote-cast-receiver");
return a?a.friendlyName:null},vxa=function(a,b,c,d,e){mxa()?lxa(b,e)&&(J8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?bxa(a,c):(window.__onGCastApiAvailable=function(b,d){b?bxa(a,c):(M8("Failed to load cast API: "+d),L8(!1),J8(!1),g.YG("yt-remote-cast-available"),g.YG("yt-remote-cast-receiver"),Xwa(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):dxa():oxa())):C8("Cannot initialize because not running Chrome")},
wxa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yg(a)||"";b&&(this.port=":"+b);this.domain=g.xg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},xxa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},j9=function(){var a=txa();
!a&&N8()&&uxa()&&(a={key:"cast-selector-receiver",name:uxa()});return a},yxa=function(){var a=gxa();
N8()&&g.XG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},zxa=function(a){var b={device:"Desktop",
app:"youtube-desktop"},b=g.XD("MDX_CONFIG")||b;g.UG&&Swa();g.DH();U8||(U8=new wxa(b?b.loungeApiHost:void 0),g.LH()&&(U8.g="/api/loungedev"));R8||(R8=g.v("yt.mdx.remote.deferredProxies_")||[],g.qa("yt.mdx.remote.deferredProxies_",R8,void 0));qxa();var c=I8();if(!c){var d=new g.WH(U8);g.qa("yt.mdx.remote.screenService_",d,void 0);c=I8();vxa(a,d,function(a){a?G8()&&i9(G8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.qG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0)}b&&!g.v("yt.mdx.remote.initialized_")&&(g.qa("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.pg(b)),k9.push(g.mG("yt-remote-cast2-availability-change",function(){g.qG("yt-remote-receiver-availability-change")})),k9.push(g.mG("yt-remote-cast2-receiver-selected",function(){F8(null);
g.qG("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.mG("yt-remote-cast2-receiver-resumed",function(){g.qG("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.mG("yt-remote-cast2-session-change",sxa)),k9.push(g.mG("yt-remote-connection-change",function(a){a?i9(G8(),"YouTube TV"):W8()||(i9(null,null),nxa())})),a=Q8(),b.isAuto&&(a.id+="#dial"),g.iF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),X8(" -- with channel params: "+
g.pg(a)),pxa(a),c.start(),G8()||rxa())},l9=function(){N8()?D8()?K8()?(C8("Requesting cast selector."),D8().requestSession()):(C8("Wait for cast API to be ready to request the session."),O8.push(g.mG("yt-remote-cast2-api-ready",l9))):M8("requestCastSelector: Cast is not initialized."):M8("requestCastSelector: Cast API is not installed!")},m9=function(a,b,c){g.K.call(this);
this.F=a;this.V=b;this.o=new g.XF(this);g.L(this,this.o);this.o.R(b,"onCaptionsTrackListChanged",this.bP);this.o.R(b,"captionschanged",this.NN);this.o.R(b,"captionssettingschanged",this.WB);this.o.R(b,"videoplayerreset",this.Wn);this.o.R(b,"mdxautoplaycancel",this.BG);this.O=this.o.R(b,"onVolumeChange",this.qA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.BA,this);c.subscribe("remotePlayerChange",this.il,this);c.subscribe("remoteQueueChange",this.Wn,this);c.subscribe("autoplayUpNext",this.dA,
this);c.subscribe("previousNextChange",this.yA,this);c.subscribe("nowAutoplaying",this.rA,this);c.subscribe("autoplayDismissed",this.cA,this);this.suggestion=null;this.G=new g.dQ(64);this.A=new g.Bt(this.RB,500,this);g.L(this,this.A);this.B=new g.Bt(this.SB,1E3,this);g.L(this,this.B);this.C={};this.K=new g.Bt(this.jC,1E3,this);g.L(this,this.K);this.J=new g.jk(this.LL,1E3,this);g.L(this,this.J);this.M=g.x;this.WB();this.Wn();this.il()},n9=function(a,b){var c=a.F,d=a.V.ha().lengthSeconds;
c.J=b||0;c.g.Y("progresssync",b,d)},Axa=function(a){n9(a,0);
a.A.stop();o9(a,new g.dQ(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.V.mi()},g.$b(c,b));a.g.KB(a.V.ha().videoId,c);a.C=b9(a.g).o}},r9=function(a,b){var c=a.V.Qf();
c?ixa(a.g,a.V.ha().videoId,b,c.de(),c.listId.toString()):ixa(a.g,a.V.ha().videoId,b);o9(a,new g.dQ(1))},Bxa=function(a,b){if(b){var c=a.V.yc("captions","tracklist",{Vx:1});
c&&c.length?(a.V.Dd("captions","track",b),a.D=!1):(a.V.Ok("captions"),a.D=!0)}else a.V.Dd("captions","track",{})},p9=function(a){return b9(a.g).videoId==a.V.ha().videoId},o9=function(a,b){a.B.stop();
var c=a.G;if(!g.jQ(c,b)){var d=g.V(b,2);if(d!=g.V(a.G,2)){var e=a.V;g.Z1(e.app,d,e.playerType)}a.G=b;Cxa(a.F,c,b)}},s9=function(a){g.X.call(this,{H:"div",
N:"ytp-remote",L:[{H:"div",N:"ytp-remote-display-status",L:[{H:"div",N:"ytp-remote-display-status-icon",L:[g.bE()]},{H:"div",N:"ytp-remote-display-status-text",L:["{{statustext}}"]}]}]});this.o=new g.RV(this,250);g.L(this,this.o);this.A=a;this.R(a,"presentingplayerstatechange",this.B);Dxa(this,g.SU(a))},Dxa=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name},c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.xb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ga("statustext",c);a.o.show()}else a.o.hide()},t9=function(a){g.AV.call(this,a);
this.A={key:g.tH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.dQ(64);this.J=0;var b=g.LU(a).D;b&&(b=b.A&&b.A.g)&&(b=new A8(a,b),g.L(this,b));b=new s9(a);g.L(this,b);g.mV(a,b.element,4)},Cxa=function(a,b,c){a.F=c;
a.g.Y("presentingplayerstatechange",new g.oQ(c,b))},u9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)Z8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ha().videoId;if(c||d){var e=a.g.Qf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.gc(k).videoId}else f=[a.g.ha().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Iy(),0),currentTime:a.g.getCurrentTime()}}else c=null;X8("Connecting to: "+g.pg(b));"cast-selector-receiver"==b.key?(F8(c||null),c=c||null,K8()?D8().setLaunchParams(c):M8("setLaunchParams called before ready.")):!c&&Y8()&&G8()==b.key?g.qG("yt-remote-connection-change",!0):
(Z8(),F8(c||null),c=I8().fe(),(c=g.vH(c,b.key))&&V8(c,1))}};
g.p(A8,g.Z0);A8.prototype.J=function(){var a=this.V.yc("remote","receivers");a&&1<a.length&&!this.V.yc("remote","quickCast")?(this.F=g.Db(a,this.B,this),g.a1(this,(0,g.H)(a,this.B)),a=this.V.yc("remote","currentReceiver"),g.$0(this,this.B(a)),this.enable(!0)):this.enable(!1)};
A8.prototype.B=function(a){return a.key};
A8.prototype.mf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
A8.prototype.sd=function(a){g.Z0.prototype.sd.call(this,a);this.V.Dd("remote","currentReceiver",this.F[a]);this.A.Vb()};
g.z(B8,g.wH);g.h=B8.prototype;g.h.fe=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.Uo=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Do=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;B8.aa.X.call(this)};
g.h.xT=function(){this.Y("screenChange")};
g.h.HP=function(){this.Y("onlineScreenChange")};
var H8=null,O8=[],R8=null,U8=null;g.z(a9,g.$F);g.h=a9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,h9(this,"play")):c9(this,"play"),f9(this,1,g.sI(b9(this))),this.Y("remotePlayerChange")):e9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,h9(this,"pause")):c9(this,"pause"),f9(this,2,g.sI(b9(this))),this.Y("remotePlayerChange")):e9(this,this.pause)};
g.h.wC=function(a){if(1==this.g){if(this.o){var b=b9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.xb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,h9(this,"seekTo",{newTime:a}))}else c9(this,"seekTo",{newTime:a});f9(this,3,a);this.Y("remotePlayerChange")}else e9(this,g.za(this.wC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,h9(this,"stopVideo")):c9(this,"stopVideo");var a=b9(this);a.index=-1;a.videoId="";g.qI(a);d9(this,a);this.Y("remotePlayerChange")}else e9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=b9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.y)(function(){g9("set receiver volume: "+d)},this),(0,g.y)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.y)(function(){g9("set receiver muted: "+b)},this),(0,g.y)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else e9(this,g.za(this.setVolume,a,b))};
g.h.KB=function(a,b){if(1==this.g){var c=b9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.pg(b.style),g.$b(d,c.o));c9(this,"setSubtitlesTrack",d);d9(this,c)}else e9(this,g.za(this.KB,a,b))};
g.h.Xt=function(a,b){if(1==this.g){c9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Tc.id});var c=b9(this);c.audioTrackId=b.Tc.id;d9(this,c)}else e9(this,g.za(this.Xt,a,b))};
g.h.vC=function(a,b){if(1==this.g){if(a&&b){var c=b9(this);g.tI(c,a,b);d9(this,c)}c9(this,"previous")}else e9(this,g.za(this.vC,a,b))};
g.h.uC=function(a,b){if(1==this.g){if(a&&b){var c=b9(this);g.tI(c,a,b);d9(this,c)}c9(this,"next")}else e9(this,g.za(this.uC,a,b))};
g.h.uw=function(){1==this.g?c9(this,"dismissAutoplay"):e9(this,this.uw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.Y("proxyStateChange",a,this.g)}a9.aa.dispose.call(this)};
g.h.X=function(){jxa(this);this.B=null;this.C.clear();$8(this,null);a9.aa.X.call(this)};
g.h.Yt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.Y("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.NB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.ZP=function(a,b){this.Y(a,b)};
g.h.PN=function(a){if(!a)this.bl(null),$8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)g9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.h.bl=function(a){g9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),kxa(this),this.Y("remotePlayerChange")};
g.h.ON=function(a){a?(kxa(this),this.Y("remotePlayerChange")):this.bl(null)};
g.h.cO=function(){var a=cxa();a&&$8(this,a)};
g.h.jc=function(a){g.jH("CP",a)};
var k9=[];g.h=wxa.prototype;g.h.Xh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Fg(b+a,{})};
g.h.Wt=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Lb:g.za(this.sT,c,!0),onError:g.za(this.rT,d),fd:g.za(this.tT,d)};b&&(c.Pb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.UE(a,c)};
g.h.sT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.rT=function(a,b){a(Error("Request error: "+b.status))};
g.h.tT=function(a){a(Error("request timed out"))};g.p(m9,g.K);g.h=m9.prototype;g.h.X=function(){g.K.prototype.X.call(this);this.A.stop();this.B.stop();this.M();this.g.unsubscribe("proxyStateChange",this.BA,this);this.g.unsubscribe("remotePlayerChange",this.il,this);this.g.unsubscribe("remoteQueueChange",this.Wn,this);this.g.unsubscribe("autoplayUpNext",this.dA,this);this.g.unsubscribe("previousNextChange",this.yA,this);this.g.unsubscribe("nowAutoplaying",this.rA,this);this.g.unsubscribe("autoplayDismissed",this.cA,this);this.g=this.F=null};
g.h.fz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(1081!=b9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":b9(this.g).xb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.aj(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.Xt(this.V.ha().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":r9(this,this.V.getCurrentTime());break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.Xt(this.V.ha().videoId,c)}};
g.h.NN=function(a){this.fz("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.WB=function(){var a=this.V.yc("captions","track");g.Ub(a)||q9(this,a)};
g.h.qA=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.il,this);var b=Math.round(a.volume);a=!!a.muted;var c=b9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.il,this)}};
g.h.bP=function(){g.Ub(this.C)||Bxa(this,this.C);this.D=!1};
g.h.BA=function(a,b){this.B.stop();2==b&&this.SB()};
g.h.il=function(){if(p9(this)){this.A.stop();var a=b9(this.g);switch(a.g){case 1081:o9(this,new g.dQ(8));break;case 1:this.RB();o9(this,new g.dQ(8));break;case 1083:case 3:o9(this,new g.dQ(9));break;case 0:o9(this,new g.dQ(2));this.J.stop();n9(this,this.V.ha().lengthSeconds);break;case 1082:o9(this,new g.dQ(4));break;case 2:o9(this,new g.dQ(4));n9(this,g.sI(a));break;case -1:o9(this,new g.dQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},o9(this,new g.dQ(128,
a))}var a=b9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Bxa(this,a));a=b9(this.g);-1==a.volume||Math.round(this.V.getVolume())==a.volume&&this.V.Me()==a.muted||this.K.isActive()||this.jC()}else Axa(this)};
g.h.yA=function(){this.V.Y("mdxpreviousnextchange")};
g.h.Wn=function(){p9(this)||Axa(this)};
g.h.BG=function(){this.g.uw()};
g.h.dA=function(a){a&&(a=g.UE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Lb:(0,g.y)(this.bR,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.bR=function(a,b){var c=new g.sP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.V.Y("mdxautoplayupnext",c)};
g.h.rA=function(a){(0,window.isNaN)(a)||this.V.Y("mdxnowautoplaying",a)};
g.h.cA=function(){this.V.Y("mdxautoplaycanceled")};
g.h.LL=function(a,b){-1==b9(this.g).g?r9(this,a):b&&this.g.wC(a)};
g.h.jC=function(){if(p9(this)){var a=b9(this.g);this.o.Ca(this.O);a.muted?this.V.mute():this.V.yg();this.V.setVolume(a.volume);this.O=this.o.R(this.V,"onVolumeChange",this.qA)}};
g.h.RB=function(){this.A.stop();if(!this.g.oa()){var a=b9(this.g);a.xb()&&o9(this,new g.dQ(8));n9(this,g.sI(a));this.A.start()}};
g.h.SB=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(s9,g.X);s9.prototype.B=function(a){Dxa(this,a.state)};g.p(t9,g.AV);g.h=t9.prototype;g.h.create=function(){zxa("embedded"==g.W(this.g).g);this.D.push(g.mG("yt-remote-before-disconnect",this.KN,this));this.D.push(g.mG("yt-remote-connection-change",this.jQ,this));this.D.push(g.mG("yt-remote-receiver-availability-change",this.zA,this));this.D.push(g.mG("yt-remote-auto-connect",this.hQ,this));this.D.push(g.mG("yt-remote-receiver-resumed",this.gQ,this));this.zA()};
g.h.load=function(){this.g.Pp();g.AV.prototype.load.call(this);this.C=new m9(this,this.g,this.o);var a=axa(),a=a?a.currentTime:0,b=Y8()?new a9(E8(),void 0):null;0==a&&b&&(a=g.sI(b9(b)));0!=a&&(this.J=a||0,this.g.Y("progresssync",a,void 0));Cxa(this,this.F,this.F);g.d2(this.g.app,6)};
g.h.unload=function(){this.g.Y("mdxautoplaycanceled");this.B=this.A;g.Qe(this.C,this.o);this.o=this.C=null;g.AV.prototype.unload.call(this);g.d2(this.g.app,5)};
g.h.X=function(){g.nG(this.D);g.AV.prototype.X.call(this)};
g.h.Tk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.fz.apply(this.C,[].concat([a],c instanceof Array?c:xxa(g.ia(c))))};
g.h.nH=function(){return this.loaded?this.C.suggestion:null};
g.h.Kf=function(){return this.o?b9(this.o).Kf:!1};
g.h.hasNext=function(){return this.o?b9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.qL=function(){var a=b9(this.o),b=this.g.ha();return{allowSeeking:this.g.Pd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.rL=function(){this.o&&this.o.uC()};
g.h.sL=function(){this.o&&this.o.vC()};
g.h.KN=function(a){1==a&&(this.K=this.o?b9(this.o):null)};
g.h.jQ=function(){var a=Y8()?new a9(E8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Pe(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ha().videoId&&this.g.Gy(a.videoId,g.sI(a)));this.g.Y("videodatachange","newdata",this.g.ha(),3)};
g.h.zA=function(){this.G=[this.A].concat(yxa());var a=j9()||this.A;u9(this,a);this.g.ya("onMdxReceiversChange")};
g.h.hQ=function(){var a=j9();u9(this,a)};
g.h.gQ=function(){this.B=j9()};
g.h.pL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l9():u9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l9(),!0):!1}};
g.h.tL=function(){c9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Fd=function(){return!1};g.WV("remote",t9);})(_yt_player);
